---
- name: configure controller
  hosts: localhost
  vars:
    controller_validate_certs: false
    controller_hostname: "{{ controller_host }}"
    controller_username: "{{ controller_user }}"
    controller_password: "{{ controller_pass }}"
  collections:
    - automation.controller
    - redhat_cop.controller_configuration
  roles: 
    - dispatch
