---
controller_credential_types:
  - name: "servicenow credential"
    description: ""
    kind: "cloud"
    inputs:
      fields:
      - id: SN_USERNAME
        label: Username
        type: string
      - id: SN_PASSWORD
        label: Password
        secret: true
        type: string
      - id: SN_HOST
        label: Host
        type: string
      required:
      - SN_USERNAME
      - SN_PASSWORD
      - SN_HOST
    injectors:
      env:
        SN_USERNAME: !unsafe "{{ SN_USERNAME }}"
        SN_PASSWORD: !unsafe "{{ SN_PASSWORD }}"
        SN_HOST: !unsafe "{{ SN_HOST }}"
