---
- name: catch generic rules
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: here is my specific rule match for a particular message
      condition: event.payload.message == "Ansible is super cool"
      action:
        debug:
          msg: "Ansible is cool"

    - name: here is a generic rule that will only match if rules above don't trigger actions
      condition: event.payload.message is defined
      action:
        debug:
          msg: "I'm diverting this to someone who cares"
