---
- name: listen for Dynatrace events
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from dynatrace
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:

  ## OS Service Monitoring

  rules:
    - name: Windows OS Service Monitoring
      condition: event.payload.State == "OPEN" and event.payload.ProblemDetails.rankedEvents is search("Auto-start Windows OS Services")
      action:
        run_job_template:
          name: Windows EDA Dynatrace Service Restart
          organization: Default

    - name: Linux OS Service Monitoring
      condition: event.payload.State == "OPEN" and event.payload.ProblemDetails.rankedEvents is search("Auto-start Linux OS Services")
      action:
        run_job_template:
          name: Linux EDA Dynatrace Service Restart
          organization: Default
