---
- name: listen for requests from ServiceNow
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from servicenow business rules
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 3000
      filters:
       - ansible.eda.normalize_keys:

  ## OS Linux Requests

  rules:
    - name: Linux EDA ServiceNow catalog example
      condition: event.payload.number is defined
      action:
        run_job_template:
          name: Linux EDA Add User
          organization: Default
