---
- name: listen for incidents from ServiceNow
  hosts: all

  ## Define our source for events

  sources:
    - name: webhook from servicenow business rules
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
       - ansible.eda.normalize_keys:

  ## OS Service Monitoring

  rules:
    - name: Linux EDA Service restarts
      condition: event.payload.number is defined and event.payload.short_description is search("Linux Service is not running", ignorecase=true)
      action:
        run_job_template:
          name: Linux EDA Restart Service
          organization: Default

    - name: Linux EDA disk pressure
      condition: event.payload.number is defined and event.payload.short_description is search("Linux Filesystem", ignorecase=true)
      action:
        run_job_template:
          name: Linux EDA Filesystem
          organization: Default
