---

- name: create incident in servicenow
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create incident
    servicenow.itsm.incident:
      state: new
      short_description: "{{ incident_description }}"
      description: "{{ incident_description }}"
      impact: low
      urgency: low
      other:
        cmdb_ci: "{{ incident_ci }}"
        assignment_group: eda
    register: incident_number
    retries: 5
    delay: 10
    until: incident_number is not failed

  - debug:
      var: incident_number.record.number
