---

- name: restart systemd service after eda event
  hosts: "{{ ansible_eda.event.payload.commonLabels.instance.split(':')[0] }}"
  tasks:
  - name: restart chronyd
    ansible.builtin.debug:
      msg: restarting stuff
